import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import { UpperNavProvider } from "./context/UpperNavContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="https://use.typekit.net/YOUR_KIT_ID.js" strategy="afterInteractive" />
        <Script
          id="typekit-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `try{Typekit.load({ async: true });}catch(e){}`

          }}
        />
      </head>
      <body className="antialiased">
        <UpperNavProvider>
          {children}
        </UpperNavProvider>
      </body>
    </html>
  );
}