import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://use.typekit.net/YOUR_KIT_ID.js"></script>
        <script dangerouslySetInnerHTML={{
          __html: `try{Typekit.load({ async: true });}catch(e){}`
        }} />
      </head>
      <body className="antialiased" style={{ fontFamily: '"futura-pt", sans-serif' }}>
        {children}
      </body>
    </html>
  );
}